### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by cihanzengin** [andbet39/accountTutorial#1]
Hello, thanks for tutorial. I did everything how you tell, and all my files same with yours. 
but i get this error i can't understand why :(

```
=> Started proxy.                             
=> Started MongoDB.                           
W20160125-22:47:19.548(2)? (STDERR)           
W20160125-22:47:19.550(2)? (STDERR) /Users/mac/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160125-22:47:19.550(2)? (STDERR)                         throw(ex);
W20160125-22:47:19.550(2)? (STDERR)                               ^
W20160125-22:47:19.550(2)? (STDERR) ReferenceError: Template is not defined
W20160125-22:47:19.550(2)? (STDERR)     at accountView.js:1:1
W20160125-22:47:19.550(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/app/accountView.js:65:4
W20160125-22:47:19.550(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/boot.js:242:10
W20160125-22:47:19.551(2)? (STDERR)     at Array.forEach (native)
W20160125-22:47:19.551(2)? (STDERR)     at Function._.each._.forEach (/Users/mac/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160125-22:47:19.551(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20160125-22:47:24.588(2)? (STDERR)           
W20160125-22:47:24.589(2)? (STDERR) /Users/mac/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160125-22:47:24.589(2)? (STDERR)                         throw(ex);
W20160125-22:47:24.589(2)? (STDERR)                               ^
W20160125-22:47:24.603(2)? (STDERR) ReferenceError: Template is not defined
W20160125-22:47:24.603(2)? (STDERR)     at accountView.js:1:1
W20160125-22:47:24.603(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/app/accountView.js:65:4
W20160125-22:47:24.604(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/boot.js:242:10
W20160125-22:47:24.604(2)? (STDERR)     at Array.forEach (native)
W20160125-22:47:24.604(2)? (STDERR)     at Function._.each._.forEach (/Users/mac/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160125-22:47:24.604(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20160125-22:47:29.402(2)? (STDERR)           
W20160125-22:47:29.402(2)? (STDERR) /Users/mac/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160125-22:47:29.402(2)? (STDERR)                         throw(ex);
W20160125-22:47:29.402(2)? (STDERR)                               ^
W20160125-22:47:29.417(2)? (STDERR) ReferenceError: Template is not defined
W20160125-22:47:29.417(2)? (STDERR)     at accountView.js:1:1
W20160125-22:47:29.417(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/app/accountView.js:65:4
W20160125-22:47:29.417(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/boot.js:242:10
W20160125-22:47:29.417(2)? (STDERR)     at Array.forEach (native)
W20160125-22:47:29.418(2)? (STDERR)     at Function._.each._.forEach (/Users/mac/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160125-22:47:29.418(2)? (STDERR)     at /Users/mac/Desktop/meteor/accounTutorial/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by gustawdaniel** [comment]
Confirmed. I have the same bug: "TypeError: Template.hello is undefined", I will fix it.

After removing lines connected with not existing hello template I obtained error:

    Error: Handler with name 'route' already exists.

I found

> https://stackoverflow.com/questions/36031706/middleware-stack-js31-uncaught-error-handler-with-name-route-already-exists

And:

> https://github.com/iron-meteor/iron-router/issues/1513

Following after instructions I updated these packages:

```
iron:core              upgraded from 1.0.7 to 1.0.11
iron:middleware-stack  upgraded from 1.0.7 to 1.1.0
iron:url               upgraded from 1.0.7 to 1.0.11
```

That was not last error. Then I have seen the following:

    Error: No Iron.Layout found so you can't use yield!

I fixed also this error removing <body> and configuring layout of Iron Router.
